# Generated by Django 4.0.5 on 2022-07-05 21:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('Billing_address', models.CharField(max_length=100)),
                ('is_closed', models.BooleanField()),
                ('opend', models.DateTimeField(auto_now=True)),
                ('closed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.DateField(auto_now=True)),
                ('shipped', models.DateField()),
                ('sip_to', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('New', 'NEW'), ('Hold', 'HOLD'), ('shipped', 'SHIPPED'), ('delivered', 'DELIVERED'), ('closed', 'CLOSED')], max_length=50)),
                ('Accnt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstquiz.account', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('name', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='webUser',
            fields=[
                ('login_id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('Password', models.CharField(editable=False, max_length=20)),
                ('State', models.CharField(choices=[('new', 'NEW'), ('Active', 'ACTIVE'), ('Blocked', 'BLOCKED'), ('Banned', 'BANNED')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shoping_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_Date', models.DateTimeField(auto_now=True)),
                ('WebUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstquiz.webuser')),
                ('accnt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstquiz.account')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('paid_Date', models.DateTimeField(auto_now=True)),
                ('acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstquiz.account')),
                ('ordr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstquiz.order')),
            ],
        ),
        migrations.CreateModel(
            name='Line_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstquiz.order')),
                ('prodct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstquiz.product')),
                ('shopingCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstquiz.shoping_cart')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('address', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('web', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstquiz.webuser')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='cust',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstquiz.customer'),
        ),
    ]
